---

- name: Install Firewall
  apt: update_cache=yes state=present pkg=ufw

- name: Allow ssh and http(s) connections
  ufw: rule=allow port={{ item }}
  with_items:
    - '22'
    - '80'
    - '443'

- name: Enable ufw/firewall
  ufw: state=enabled policy=deny

